apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysqldb
            - name: DB_NAME
              value: bezkoder_db
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: MYSQLDB_DATABASE
              value: bezkoder_db
            - name: MYSQLDB_DOCKER_PORT
              value: "3306"
            - name: MYSQLDB_LOCAL_PORT
              value: "3307"
            - name: MYSQLDB_ROOT_PASSWORD
              value: "123456"
            - name: MYSQLDB_USER
              value: root
            - name: NODE_DOCKER_PORT
              value: "8080"
            - name: NODE_LOCAL_PORT
              value: "6868"
          image: alsonchang/nodejsapp
          name: app
          ports:
            - containerPort: 8080
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
