services:
  app:
    build:
      context: ./bezkoder-app
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_NAME: bezkoder_db
      DB_PASSWORD: '123456'
      DB_PORT: '3306'
      DB_USER: root
      MYSQLDB_DATABASE: bezkoder_db
      MYSQLDB_DOCKER_PORT: '3306'
      MYSQLDB_LOCAL_PORT: '3307'
      MYSQLDB_ROOT_PASSWORD: '123456'
      MYSQLDB_USER: root
      NODE_DOCKER_PORT: '8080'
      NODE_LOCAL_PORT: '6868'
    ports:
      - 6868:8080
    restart: unless-stopped
    stdin_open: true
    tty: true
  mysqldb:
    environment:
      MYSQLDB_DATABASE: bezkoder_db
      MYSQLDB_DOCKER_PORT: '3306'
      MYSQLDB_LOCAL_PORT: '3307'
      MYSQLDB_ROOT_PASSWORD: '123456'
      MYSQLDB_USER: root
      MYSQL_DATABASE: bezkoder_db
      MYSQL_ROOT_PASSWORD: '123456'
      NODE_DOCKER_PORT: '8080'
      NODE_LOCAL_PORT: '6868'
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql:rw
version: '3'
volumes:
  db: {}
