apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
        - env:
            - name: MYSQLDB_DATABASE
              value: bezkoder_db
            - name: MYSQLDB_DOCKER_PORT
              value: "3306"
            - name: MYSQLDB_LOCAL_PORT
              value: "3307"
            - name: MYSQLDB_ROOT_PASSWORD
              value: "123456"
            - name: MYSQLDB_USER
              value: root
            - name: MYSQL_DATABASE
              value: bezkoder_db
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: NODE_DOCKER_PORT
              value: "8080"
            - name: NODE_LOCAL_PORT
              value: "6868"
          image: mysql:5.7
          name: mysqldb
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
